# =============================================================================
# Sotorasib Interactive E-R Explorer — Shiny App
# =============================================================================
# Interactive viewer on top of validated Python pipeline outputs.
# Reads CSV files generated by the Python scripts — no re-simulation in R.
# Model parameters read from model_params.csv (not hard-coded).
# =============================================================================

library(shiny)
library(bslib)
library(DT)
library(plotly)
library(readr)
library(dplyr)
library(tidyr)

# --- Paths -------------------------------------------------------------------
APP_DIR <- tryCatch(
  dirname(normalizePath(sys.frame(1)$ofile, mustWork = FALSE)),
  error = function(e) getwd()
)
if (is.na(APP_DIR) || APP_DIR == "") APP_DIR <- getwd()
PROJECT_ROOT <- dirname(APP_DIR)
TABLES_DIR <- file.path(PROJECT_ROOT, "outputs", "tables")

# --- Required CSV Files ------------------------------------------------------
REQUIRED_FILES <- c(
  "virtual_patients.csv",
  "pk_summary_by_dose.csv",
  "pk_anchor_vs_simulated.csv",
  "orr_by_exposure_quartile.csv",
  "safety_by_exposure_quartile.csv",
  "dose_optimization_summary.csv",
  "benefit_risk_comparison.csv",
  "covariate_effects.csv",
  "model_params.csv"
)

# --- Check pipeline status ---------------------------------------------------
check_pipeline <- function() {
  missing <- REQUIRED_FILES[!file.exists(file.path(TABLES_DIR, REQUIRED_FILES))]
  list(ok = length(missing) == 0, missing = missing)
}

# --- E-R Model Functions (parameters read from CSV) --------------------------
# These are used for the "What-If" overlay predictions
p_response <- function(auc, E0, Emax, EC50, gamma) {
  if (auc <= 0) return(E0)
  E0 + Emax * auc^gamma / (EC50^gamma + auc^gamma)
}

p_hepatotox <- function(cmax, prior_cpi, alpha, beta_cmax, beta_cpi) {
  logit_p <- alpha + beta_cmax * cmax + beta_cpi * prior_cpi
  1 / (1 + exp(-logit_p))
}

# --- Dose colors (match Python pipeline) -------------------------------------
DOSE_COLORS <- c(
  "180" = "#1f77b4", "240" = "#ff7f0e", "360" = "#2ca02c",
  "720" = "#d62728", "960" = "#9467bd"
)

# =============================================================================
# UI — Pipeline Not Run Screen
# =============================================================================

pipeline_not_run_ui <- function(missing_files) {
  page_fillable(
    theme = bs_theme(bootswatch = "flatly", version = 5),
    layout_columns(
      col_widths = c(3, 6, 3),
      "",
      card(
        class = "mt-5",
        card_header(
          class = "bg-warning text-dark",
          tags$h3(class = "mb-0", "Pipeline Not Run")
        ),
        card_body(
          tags$p(class = "fs-5 mt-3",
            "The Python analysis pipeline has not been run yet. ",
            "This Shiny app reads the CSV outputs generated by the pipeline."
          ),
          tags$p(tags$strong("Missing files:")),
          tags$ul(lapply(missing_files, function(f) tags$li(tags$code(f)))),
          tags$hr(),
          tags$p("Run the pipeline with:"),
          tags$pre(
            class = "bg-dark text-light p-3 rounded",
            "cd 05-sotorasib-exposure-response && bash run_all.sh"
          ),
          tags$hr(),
          actionButton("recheck", "Re-check Files", class = "btn-primary btn-lg")
        )
      ),
      ""
    )
  )
}

# =============================================================================
# UI — Main App
# =============================================================================

main_app_ui <- function() {
  page_sidebar(
    title = "Sotorasib Interactive E-R Explorer",
    theme = bs_theme(bootswatch = "flatly", version = 5),

    sidebar = sidebar(
      width = 300,

      h6("Dose Selection"),
      radioButtons("dose", "Dose (mg)",
        choices = c(180, 240, 360, 720, 960),
        selected = 960, inline = TRUE
      ),

      hr(),
      h6("Patient Profile"),
      selectInput("ecog", "ECOG Status", choices = c("All" = "all", "0" = "0", "1" = "1", "2" = "2"), selected = "all"),
      checkboxInput("cpi", "Prior CPI", value = FALSE),

      hr(),
      checkboxInput("compare_mode", "Compare with second dose", value = FALSE),
      conditionalPanel(
        condition = "input.compare_mode",
        radioButtons("dose2", "Comparison Dose (mg)",
          choices = c(180, 240, 360, 720, 960),
          selected = 240, inline = TRUE
        )
      ),

      hr(),
      tags$details(
        tags$summary(tags$strong("Advanced: Manual Exposure Input")),
        numericInput("manual_auc", "AUC (hr*ug/mL)", value = NA_real_, min = 0),
        numericInput("manual_cmax", "Cmax (ug/mL)", value = NA_real_, min = 0),
        tags$small(class = "text-muted", "Overrides covariate filtering for E-R evaluation")
      )
    ),

    # Main panel
    layout_columns(
      col_widths = 12,

      # Top metrics card
      uiOutput("metrics_card"),

      # Tabbed panels
      navset_card_tab(
        id = "main_tabs",

        nav_panel(
          "Dose-Exposure",
          plotlyOutput("exposure_boxplot", height = "450px"),
          br(),
          uiOutput("pk_validation_table")
        ),

        nav_panel(
          "Efficacy",
          layout_columns(
            col_widths = c(6, 6),
            plotlyOutput("orr_by_dose", height = "350px"),
            plotlyOutput("orr_by_quartile", height = "350px")
          ),
          br(),
          plotlyOutput("er_curve_efficacy", height = "350px")
        ),

        nav_panel(
          "Safety",
          layout_columns(
            col_widths = c(6, 6),
            plotlyOutput("safety_quartile", height = "350px"),
            uiOutput("risk_matrix")
          ),
          br(),
          uiOutput("subset_risk_card")
        ),

        nav_panel(
          "Benefit-Risk",
          plotlyOutput("benefit_risk_scatter", height = "450px"),
          br(),
          DTOutput("br_metrics_table"),
          br(),
          downloadButton("download_csv", "Download Dose Comparison CSV", class = "btn-primary")
        )
      )
    )
  )
}

# =============================================================================
# UI Function (dynamic)
# =============================================================================

ui <- function(req) {
  status <- check_pipeline()
  if (!status$ok) {
    pipeline_not_run_ui(status$missing)
  } else {
    main_app_ui()
  }
}

# =============================================================================
# SERVER
# =============================================================================

server <- function(input, output, session) {

  # --- Re-check button (pipeline not run screen) ----------------------------
  observeEvent(input$recheck, {
    session$reload()
  })

  # --- Load all CSV data once ------------------------------------------------
  status <- check_pipeline()
  if (!status$ok) return()

  vp <- read_csv(file.path(TABLES_DIR, "virtual_patients.csv"), show_col_types = FALSE)
  pk_summary <- read_csv(file.path(TABLES_DIR, "pk_summary_by_dose.csv"), show_col_types = FALSE)
  pk_anchors <- read_csv(file.path(TABLES_DIR, "pk_anchor_vs_simulated.csv"), show_col_types = FALSE)
  orr_quartile <- read_csv(file.path(TABLES_DIR, "orr_by_exposure_quartile.csv"), show_col_types = FALSE)
  safety_quartile <- read_csv(file.path(TABLES_DIR, "safety_by_exposure_quartile.csv"), show_col_types = FALSE)
  dose_summary <- read_csv(file.path(TABLES_DIR, "dose_optimization_summary.csv"), show_col_types = FALSE)
  br_comparison <- read_csv(file.path(TABLES_DIR, "benefit_risk_comparison.csv"), show_col_types = FALSE)
  covariate_effects <- read_csv(file.path(TABLES_DIR, "covariate_effects.csv"), show_col_types = FALSE)
  model_params <- read_csv(file.path(TABLES_DIR, "model_params.csv"), show_col_types = FALSE)

  # Extract model parameters from CSV
  get_param <- function(model_name, param_name) {
    row <- model_params %>% filter(model == model_name, parameter == param_name)
    if (nrow(row) == 0) return(NA_real_)
    row$value[1]
  }

  E0 <- get_param("efficacy", "E0")
  Emax <- get_param("efficacy", "Emax")
  EC50 <- get_param("efficacy", "EC50")
  gamma_hill <- get_param("efficacy", "gamma")
  alpha_safe <- get_param("safety", "alpha")
  beta_cmax <- get_param("safety", "beta_cmax")
  beta_cpi <- get_param("safety", "beta_cpi")

  # --- Reactive: Filtered subset ---------------------------------------------
  filtered_vp <- reactive({
    dose_val <- as.numeric(input$dose)
    df <- vp %>% filter(dose_mg == dose_val)

    if (input$ecog != "all") {
      df <- df %>% filter(ecog == as.integer(input$ecog))
    }
    if (input$cpi) {
      df <- df %>% filter(prior_cpi == 1)
    }
    df
  })

  # Comparison dose filtered
  filtered_vp2 <- reactive({
    req(input$compare_mode)
    dose_val <- as.numeric(input$dose2)
    df <- vp %>% filter(dose_mg == dose_val)
    if (input$ecog != "all") {
      df <- df %>% filter(ecog == as.integer(input$ecog))
    }
    if (input$cpi) {
      df <- df %>% filter(prior_cpi == 1)
    }
    df
  })

  # --- Reactive: Predicted outcomes for subset --------------------------------
  subset_predictions <- reactive({
    fvp <- filtered_vp()
    if (nrow(fvp) == 0) return(list(n = 0, median_auc = NA, median_cmax = NA,
                                     pred_orr = NA, pred_hepatotox = NA))

    # Check for manual override
    use_manual <- !is.na(input$manual_auc) && !is.na(input$manual_cmax)
    if (use_manual) {
      auc_val <- input$manual_auc
      cmax_val <- input$manual_cmax
      cpi_val <- as.numeric(input$cpi)
    } else {
      auc_val <- median(fvp$auc_ss)
      cmax_val <- median(fvp$cmax_ss)
      cpi_val <- as.numeric(input$cpi)
    }

    pred_orr <- p_response(auc_val, E0, Emax, EC50, gamma_hill) * 100
    pred_hep <- p_hepatotox(cmax_val, cpi_val, alpha_safe, beta_cmax, beta_cpi) * 100

    list(
      n = nrow(fvp),
      median_auc = round(auc_val, 1),
      median_cmax = round(cmax_val, 2),
      pred_orr = round(pred_orr, 1),
      pred_hepatotox = round(pred_hep, 1)
    )
  })

  # --- Top Metrics Card -------------------------------------------------------
  output$metrics_card <- renderUI({
    sp <- subset_predictions()
    dose_val <- input$dose
    dose_row <- dose_summary %>% filter(dose_mg == as.numeric(dose_val))

    ti <- if (nrow(dose_row) > 0) dose_row$therapeutic_index[1] else NA

    profile_text <- paste0(
      "N = ", sp$n, " matching patients",
      if (input$ecog != "all") paste0(", ECOG ", input$ecog) else "",
      if (input$cpi) ", Prior CPI" else ""
    )

    card(
      card_body(
        layout_columns(
          col_widths = c(2, 3, 3, 2, 2),
          value_box(title = "Dose", value = paste0(dose_val, " mg"), theme = "primary"),
          value_box(title = "Predicted ORR", value = paste0(sp$pred_orr, "%"),
                    theme = if (!is.na(sp$pred_orr) && sp$pred_orr > 25) "success" else "warning"),
          value_box(title = "Predicted Hepatotox",
                    value = paste0(sp$pred_hepatotox, "%"),
                    theme = if (!is.na(sp$pred_hepatotox) && sp$pred_hepatotox > 20) "danger" else "success"),
          value_box(title = "Median AUC", value = sp$median_auc, theme = "light"),
          value_box(title = "TI", value = round(ti, 2), theme = "light")
        ),
        tags$p(class = "text-muted mt-1 mb-0", profile_text)
      )
    )
  })

  # --- Tab 1: Dose-Exposure ---------------------------------------------------
  output$exposure_boxplot <- renderPlotly({
    # Boxplot of AUCss by dose
    p <- plot_ly()

    for (d in c(180, 240, 360, 720, 960)) {
      sub <- vp %>% filter(dose_mg == d)
      p <- p %>% add_boxplot(
        y = sub$auc_ss, name = paste0(d, " mg"),
        marker = list(color = DOSE_COLORS[as.character(d)]),
        line = list(color = DOSE_COLORS[as.character(d)]),
        fillcolor = paste0(DOSE_COLORS[as.character(d)], "40"),
        boxpoints = FALSE
      )
    }

    # Published anchors as diamonds
    p <- p %>%
      add_markers(x = paste0(pk_anchors$dose_mg, " mg"), y = pk_anchors$published_auc,
                  marker = list(symbol = "diamond", size = 12, color = "black",
                                line = list(color = "white", width = 1)),
                  name = "Published (anchor)",
                  hovertemplate = "%{x}<br>Published AUC: %{y:.1f}<extra></extra>")

    # Highlight filtered subset
    fvp <- filtered_vp()
    if (nrow(fvp) > 0) {
      dose_label <- paste0(input$dose, " mg")
      med_auc <- median(fvp$auc_ss)
      p <- p %>% add_markers(
        x = dose_label, y = med_auc,
        marker = list(symbol = "star", size = 16, color = "#e74c3c",
                      line = list(color = "white", width = 2)),
        name = "Subset Median",
        hovertext = paste0("Subset median AUC: ", round(med_auc, 1))
      )
    }

    p %>% layout(
      title = list(text = "Steady-State AUC by Dose (Virtual Patients, N=2,500)"),
      yaxis = list(title = "AUCss (hr*ug/mL)"),
      xaxis = list(title = "Dose"),
      annotations = list(
        list(x = 0.5, y = 1.05, xref = "paper", yref = "paper",
             text = "5.3x dose range, <1.4x AUC range (saturable absorption)",
             showarrow = FALSE, font = list(size = 11, color = "gray"))
      )
    )
  })

  output$pk_validation_table <- renderUI({
    card(
      card_header("PK Calibration: Published vs Simulated"),
      card_body(
        renderDT(
          pk_anchors %>%
            mutate(auc_ratio = round(auc_ratio, 3),
                   cmax_ratio = round(cmax_ratio, 3)),
          rownames = FALSE,
          options = list(dom = 't', pageLength = 10)
        )
      )
    )
  })

  # --- Tab 2: Efficacy --------------------------------------------------------
  output$orr_by_dose <- renderPlotly({
    ds <- dose_summary

    # Published ORR for reference
    pub_orr <- tibble(
      dose_mg = c(240, 960),
      pub_orr = c(24.8, 32.7)
    )

    plot_ly(ds, x = ~factor(dose_mg), y = ~orr_pct, type = "bar",
            marker = list(
              color = DOSE_COLORS[as.character(ds$dose_mg)],
              line = list(color = "black", width = 1)
            ),
            hovertemplate = "%{x} mg<br>ORR: %{y:.1f}%<extra></extra>",
            name = "Simulated") %>%
      add_markers(data = pub_orr, x = ~factor(dose_mg), y = ~pub_orr,
                  marker = list(symbol = "diamond", size = 12, color = "black"),
                  name = "Published",
                  hovertemplate = "%{x} mg<br>Published ORR: %{y:.1f}%<extra></extra>") %>%
      layout(
        title = "ORR by Dose (model-implied, virtual patients)",
        xaxis = list(title = "Dose (mg)"),
        yaxis = list(title = "ORR (%)", range = c(0, 55)),
        showlegend = TRUE
      )
  })

  output$orr_by_quartile <- renderPlotly({
    oq <- orr_quartile

    plot_ly(oq, x = ~quartile, y = ~orr_pct, type = "bar",
            marker = list(color = "#3498db", line = list(color = "black", width = 1)),
            hovertemplate = "%{x}<br>AUC median: %{customdata:.1f}<br>ORR: %{y:.1f}%<extra></extra>",
            customdata = ~auc_median) %>%
      layout(
        title = "ORR by Exposure Quartile (960 mg)",
        xaxis = list(title = "AUC Quartile"),
        yaxis = list(title = "ORR (%)", range = c(0, 50))
      )
  })

  output$er_curve_efficacy <- renderPlotly({
    # E-R curve using model params from CSV
    auc_seq <- seq(1, 200, length.out = 200)
    orr_seq <- sapply(auc_seq, function(a) p_response(a, E0, Emax, EC50, gamma_hill) * 100)

    p <- plot_ly() %>%
      add_lines(x = auc_seq, y = orr_seq,
                line = list(color = "#2c3e50", width = 2),
                name = "E-R Model",
                hovertemplate = "AUC: %{x:.1f}<br>Predicted ORR: %{y:.1f}%<extra></extra>")

    # Add dose-level points
    for (i in seq_len(nrow(dose_summary))) {
      row <- dose_summary[i, ]
      d <- as.character(row$dose_mg)
      p <- p %>% add_markers(
        x = row$gm_auc_ss, y = row$orr_pct,
        marker = list(size = 12, color = DOSE_COLORS[d],
                      line = list(color = "black", width = 1.5)),
        name = paste0(d, " mg"),
        hovertemplate = paste0(d, " mg<br>GM AUC: %{x:.1f}<br>ORR: %{y:.1f}%<extra></extra>")
      )
    }

    # Highlight subset
    sp <- subset_predictions()
    if (!is.na(sp$median_auc) && !is.na(sp$pred_orr)) {
      p <- p %>% add_markers(
        x = sp$median_auc, y = sp$pred_orr,
        marker = list(symbol = "star", size = 16, color = "#e74c3c",
                      line = list(color = "white", width = 2)),
        name = "Your Subset",
        hovertext = paste0("Subset: AUC=", sp$median_auc, ", ORR=", sp$pred_orr, "%")
      )
    }

    p %>% layout(
      title = "Exposure-Response: ORR vs AUC",
      xaxis = list(title = "AUCss (hr*ug/mL)"),
      yaxis = list(title = "Predicted ORR (%)"),
      showlegend = TRUE,
      legend = list(x = 0.7, y = 0.3)
    )
  })

  # --- Tab 3: Safety ----------------------------------------------------------
  output$safety_quartile <- renderPlotly({
    sq <- safety_quartile

    plot_ly(sq, x = ~quartile, y = ~hepatotox_pct, type = "bar",
            marker = list(color = "#e74c3c", line = list(color = "black", width = 1)),
            hovertemplate = "%{x}<br>Cmax median: %{customdata:.1f}<br>Hepatotox: %{y:.1f}%<extra></extra>",
            customdata = ~cmax_median) %>%
      layout(
        title = "Grade 3+ Hepatotoxicity by Cmax Quartile (960 mg)",
        xaxis = list(title = "Cmax Quartile"),
        yaxis = list(title = "Hepatotoxicity Rate (%)", range = c(0, 40))
      )
  })

  output$risk_matrix <- renderUI({
    # 2x2 risk matrix: High/Low Cmax vs CPI Yes/No
    dose_val <- as.numeric(input$dose)
    sub <- vp %>% filter(dose_mg == dose_val)
    med_cmax <- median(sub$cmax_ss)

    # Compute predicted hepatotox rates for each cell
    cells <- expand.grid(cmax_level = c("Low", "High"), cpi = c(0, 1))
    cells$cmax_val <- ifelse(cells$cmax_level == "High",
                              quantile(sub$cmax_ss, 0.75),
                              quantile(sub$cmax_ss, 0.25))
    cells$rate <- sapply(seq_len(nrow(cells)), function(i) {
      round(p_hepatotox(cells$cmax_val[i], cells$cpi[i],
                         alpha_safe, beta_cmax, beta_cpi) * 100, 1)
    })

    card(
      card_header("Risk Stratification Matrix"),
      card_body(
        tags$table(
          class = "table table-bordered text-center",
          tags$thead(
            tags$tr(tags$th(""), tags$th("No Prior CPI"), tags$th("Prior CPI"))
          ),
          tags$tbody(
            tags$tr(
              tags$td(tags$strong("Low Cmax")),
              tags$td(class = "bg-success text-white", paste0(cells$rate[cells$cmax_level == "Low" & cells$cpi == 0], "%")),
              tags$td(class = "bg-warning", paste0(cells$rate[cells$cmax_level == "Low" & cells$cpi == 1], "%"))
            ),
            tags$tr(
              tags$td(tags$strong("High Cmax")),
              tags$td(class = "bg-warning", paste0(cells$rate[cells$cmax_level == "High" & cells$cpi == 0], "%")),
              tags$td(class = "bg-danger text-white", paste0(cells$rate[cells$cmax_level == "High" & cells$cpi == 1], "%"))
            )
          )
        ),
        tags$small(class = "text-muted",
                   paste0("Low/High Cmax = Q1/Q3 of ", dose_val, " mg (", round(med_cmax, 1), " ug/mL median)"))
      )
    )
  })

  output$subset_risk_card <- renderUI({
    sp <- subset_predictions()
    if (is.na(sp$pred_hepatotox)) return(NULL)

    risk_class <- if (sp$pred_hepatotox > 20) "danger"
                  else if (sp$pred_hepatotox > 10) "warning"
                  else "success"

    card(
      card_header("Subset Hepatotoxicity Prediction"),
      card_body(
        tags$div(
          class = "text-center",
          tags$span(class = paste0("badge bg-", risk_class, " fs-3 px-4 py-2"),
                    paste0(sp$pred_hepatotox, "%")),
          tags$p(class = "mt-2",
                 paste0("Predicted Grade 3+ hepatotoxicity for ",
                        ifelse(input$ecog != "all", paste0("ECOG ", input$ecog), "all ECOG"),
                        ifelse(input$cpi, ", prior CPI", ", no prior CPI"),
                        " at ", input$dose, " mg")),
          tags$p(class = "text-muted",
                 paste0("Based on median Cmax = ", sp$median_cmax, " ug/mL (N=", sp$n, " patients)"))
        )
      )
    )
  })

  # --- Tab 4: Benefit-Risk ----------------------------------------------------
  output$benefit_risk_scatter <- renderPlotly({
    ds <- dose_summary

    # Published anchors
    pub <- tibble(
      dose = c("240 (pub)", "960 (pub)"),
      hepatotox = c(14.0, 16.0),
      orr = c(24.8, 32.7)
    )

    p <- plot_ly()

    # Simulated points
    for (i in seq_len(nrow(ds))) {
      row <- ds[i, ]
      d <- as.character(row$dose_mg)
      p <- p %>% add_markers(
        x = row$hepatotox_pct, y = row$orr_pct,
        marker = list(size = 18, color = DOSE_COLORS[d],
                      line = list(color = "black", width = 1.5)),
        name = paste0(d, " mg (sim)"),
        hovertemplate = paste0(d, " mg<br>ORR: %{y:.1f}%<br>Hepatotox: %{x:.1f}%<extra></extra>")
      )
    }

    # Published points (diamonds)
    p <- p %>%
      add_markers(data = pub, x = ~hepatotox, y = ~orr,
                  marker = list(symbol = "diamond", size = 14, color = "black",
                                line = list(color = "white", width = 1)),
                  name = "Published",
                  hovertemplate = "%{text}<br>ORR: %{y:.1f}%<br>Hepatotox: %{x:.1f}%<extra></extra>",
                  text = ~dose)

    # Highlight subset position
    sp <- subset_predictions()
    if (!is.na(sp$pred_orr) && !is.na(sp$pred_hepatotox)) {
      p <- p %>% add_markers(
        x = sp$pred_hepatotox, y = sp$pred_orr,
        marker = list(symbol = "star", size = 20, color = "#e74c3c",
                      line = list(color = "white", width = 2)),
        name = "Your Subset",
        hovertext = paste0("Subset: ORR=", sp$pred_orr, "%, Hepatotox=", sp$pred_hepatotox, "%")
      )
    }

    # Diagonal NCB reference lines
    shapes <- lapply(c(0, 10, 20), function(ncb) {
      list(type = "line", x0 = 0, y0 = ncb, x1 = 30, y1 = 30 + ncb,
           line = list(color = "gray", dash = "dot", width = 0.8),
           opacity = 0.4)
    })

    p %>% layout(
      title = "Benefit-Risk: ORR vs Hepatotoxicity by Dose",
      xaxis = list(title = "Grade 3+ Hepatotoxicity (%)", range = c(0, 28)),
      yaxis = list(title = "Objective Response Rate (%)", range = c(15, 55)),
      shapes = shapes,
      showlegend = TRUE,
      legend = list(x = 0.01, y = 0.99)
    )
  })

  output$br_metrics_table <- renderDT({
    ds <- dose_summary %>%
      select(
        `Dose (mg)` = dose_mg,
        `GM AUCss` = gm_auc_ss,
        `GM Cmax` = gm_cmax_ss,
        `ORR (%)` = orr_pct,
        `Hepatotox (%)` = hepatotox_pct,
        TI = therapeutic_index,
        NNT = nnt,
        NNH = nnh,
        `NCB (%)` = net_clinical_benefit_pct
      )
    datatable(ds, rownames = FALSE, options = list(dom = 't', pageLength = 10))
  })

  # --- Download ---------------------------------------------------------------
  output$download_csv <- downloadHandler(
    filename = function() {
      paste0("sotorasib_dose_comparison_", format(Sys.Date(), "%Y%m%d"), ".csv")
    },
    content = function(file) {
      write_csv(dose_summary, file)
    }
  )
}

# =============================================================================
# Run App
# =============================================================================
shinyApp(ui = ui, server = server)
